# Generated by Django 5.2.8 on 2025-11-27 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('nisn', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='NISN harus 10 digit angka', regex='^\\d{10}$')], verbose_name='NISN')),
                ('tempat_lahir', models.CharField(max_length=100, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10, verbose_name='Jenis Kelamin')),
                ('agama', models.CharField(default='Islam', help_text='Agama santri (default: Islam)', max_length=20, verbose_name='Agama')),
                ('golongan_darah', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3, verbose_name='Golongan Darah')),
                ('tinggi_badan', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tinggi Badan (cm)')),
                ('berat_badan', models.PositiveIntegerField(blank=True, null=True, verbose_name='Berat Badan (kg)')),
                ('nama_ayah', models.CharField(max_length=200, verbose_name='Nama Ayah')),
                ('nik_ayah', models.CharField(blank=True, help_text='16 digit NIK', max_length=16, verbose_name='NIK Ayah (No. KTP)')),
                ('nama_ibu', models.CharField(max_length=200, verbose_name='Nama Ibu')),
                ('nik_ibu', models.CharField(blank=True, help_text='16 digit NIK', max_length=16, verbose_name='NIK Ibu (No. KTP)')),
                ('pekerjaan_ayah', models.CharField(blank=True, max_length=100, verbose_name='Pekerjaan Ayah')),
                ('pekerjaan_ibu', models.CharField(blank=True, max_length=100, verbose_name='Pekerjaan Ibu')),
                ('no_hp_ayah', models.CharField(blank=True, max_length=15, verbose_name='No. HP Ayah')),
                ('no_hp_ibu', models.CharField(blank=True, max_length=15, verbose_name='No. HP Ibu')),
                ('alamat_orangtua', models.TextField(blank=True, verbose_name='Alamat Orang Tua')),
                ('alamat', models.TextField(verbose_name='Alamat Lengkap')),
                ('no_hp', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Format nomor HP tidak valid', regex='^\\+?1?\\d{9,15}$')], verbose_name='No. HP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('asal_sekolah', models.CharField(max_length=200, verbose_name='Asal Sekolah')),
                ('kelas_terakhir', models.CharField(max_length=50, verbose_name='Kelas Terakhir')),
                ('tahun_lulus', models.CharField(blank=True, max_length=4, verbose_name='Tahun Lulus')),
                ('no_ijazah', models.CharField(blank=True, max_length=50, verbose_name='No. Ijazah/SKHUN')),
                ('foto_santri', models.ImageField(blank=True, null=True, upload_to='santri/foto/', verbose_name='Foto Santri')),
                ('foto_ktp', models.ImageField(blank=True, null=True, upload_to='santri/ktp/', verbose_name='Foto KTP/Kartu Keluarga')),
                ('foto_akta', models.ImageField(blank=True, null=True, upload_to='santri/akta/', verbose_name='Foto Akta Kelahiran')),
                ('foto_ijazah', models.ImageField(blank=True, null=True, upload_to='santri/ijazah/', verbose_name='Foto Ijazah/SKHUN')),
                ('surat_sehat', models.ImageField(blank=True, null=True, upload_to='santri/surat_sehat/', verbose_name='Surat Keterangan Sehat')),
                ('foto_santri_approved', models.BooleanField(default=False, verbose_name='Foto Santri Disetujui')),
                ('foto_ktp_approved', models.BooleanField(default=False, verbose_name='Foto KTP/KK Disetujui')),
                ('foto_akta_approved', models.BooleanField(default=False, verbose_name='Foto Akta Disetujui')),
                ('foto_ijazah_approved', models.BooleanField(default=False, verbose_name='Foto Ijazah Disetujui')),
                ('surat_sehat_approved', models.BooleanField(default=False, verbose_name='Surat Sehat Disetujui')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('verified', 'Pembayaran Terverifikasi'), ('accepted', 'Diterima'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Daftar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diupdate')),
            ],
            options={
                'verbose_name': 'Santri',
                'verbose_name_plural': 'Santri',
                'ordering': ['-created_at'],
            },
        ),
    ]
