# Generated by Django 5.2.8 on 2025-12-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='agama_ayah',
            field=models.CharField(blank=True, default='Islam', max_length=20, verbose_name='Agama Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='agama_ibu',
            field=models.CharField(blank=True, default='Islam', max_length=20, verbose_name='Agama Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='anak_ke',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Anak Ke'),
        ),
        migrations.AddField(
            model_name='santri',
            name='bahasa_sehari_hari',
            field=models.CharField(blank=True, default='Indonesia', max_length=50, verbose_name='Bahasa Sehari-hari'),
        ),
        migrations.AddField(
            model_name='santri',
            name='desa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Desa/Kelurahan'),
        ),
        migrations.AddField(
            model_name='santri',
            name='jumlah_saudara',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jumlah Saudara'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kabupaten'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kelas_diterima',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kelas Diterima (di Pesantren)'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kewarganegaraan',
            field=models.CharField(choices=[('WNI', 'WNI'), ('WNA', 'WNA')], default='WNI', max_length=10, verbose_name='Kewarganegaraan'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kewarganegaraan_ayah',
            field=models.CharField(blank=True, choices=[('WNI', 'WNI'), ('WNA', 'WNA')], default='WNI', max_length=10, verbose_name='Kewarganegaraan Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kewarganegaraan_ibu',
            field=models.CharField(blank=True, choices=[('WNI', 'WNI'), ('WNA', 'WNA')], default='WNI', max_length=10, verbose_name='Kewarganegaraan Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kode_pos',
            field=models.CharField(blank=True, max_length=10, verbose_name='Kode Pos'),
        ),
        migrations.AddField(
            model_name='santri',
            name='nama_panggilan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Panggilan'),
        ),
        migrations.AddField(
            model_name='santri',
            name='npsn_sekolah',
            field=models.CharField(blank=True, max_length=20, verbose_name='NPSN Sekolah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='pendidikan_ayah',
            field=models.CharField(blank=True, choices=[('SD SEDERAJAT', 'SD SEDERAJAT'), ('SMP SEDERAJAT', 'SMP SEDERAJAT'), ('SMA SEDERAJAT', 'SMA SEDERAJAT'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=50, verbose_name='Pendidikan Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='pendidikan_ibu',
            field=models.CharField(blank=True, choices=[('SD SEDERAJAT', 'SD SEDERAJAT'), ('SMP SEDERAJAT', 'SMP SEDERAJAT'), ('SMA SEDERAJAT', 'SMA SEDERAJAT'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=50, verbose_name='Pendidikan Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='santri',
            name='riwayat_penyakit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Riwayat Penyakit'),
        ),
        migrations.AddField(
            model_name='santri',
            name='status_ayah',
            field=models.CharField(blank=True, choices=[('HIDUP', 'HIDUP'), ('MENINGGAL', 'MENINGGAL')], default='HIDUP', max_length=10, verbose_name='Status Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='status_ibu',
            field=models.CharField(blank=True, choices=[('HIDUP', 'HIDUP'), ('MENINGGAL', 'MENINGGAL')], default='HIDUP', max_length=10, verbose_name='Status Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='tanggal_diterima',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Diterima'),
        ),
        migrations.AddField(
            model_name='santri',
            name='tanggal_lahir_ayah',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='tanggal_lahir_ibu',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='tempat_lahir_ayah',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir Ayah'),
        ),
        migrations.AddField(
            model_name='santri',
            name='tempat_lahir_ibu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir Ibu'),
        ),
        migrations.AddField(
            model_name='santri',
            name='tinggal_dengan',
            field=models.CharField(blank=True, choices=[('Orang Tua', 'Orang Tua'), ('Wali', 'Wali'), ('Lainnya', 'Lainnya')], max_length=50, verbose_name='Tinggal Dengan'),
        ),
    ]
