# Generated by Django 5.2.8 on 2025-11-27 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bank', models.CharField(choices=[('BCA', 'Bank Central Asia (BCA)'), ('BNI', 'Bank Negara Indonesia (BNI)'), ('BRI', 'Bank Rakyat Indonesia (BRI)'), ('Mandiri', 'Bank Mandiri'), ('BSI', 'Bank Syariah Indonesia (BSI)'), ('CIMB', 'CIMB Niaga'), ('Permata', 'Bank Permata'), ('Danamon', 'Bank Danamon'), ('Lainnya', 'Bank Lainnya')], max_length=100, verbose_name='Nama Bank')),
                ('nama_bank_custom', models.CharField(blank=True, help_text='Isi jika memilih Bank Lainnya', max_length=100, verbose_name='Nama Bank (Custom)')),
                ('nomor_rekening', models.CharField(max_length=50, verbose_name='Nomor Rekening')),
                ('nama_pemilik_rekening', models.CharField(max_length=200, verbose_name='Nama Pemilik Rekening')),
                ('biaya_pendaftaran', models.DecimalField(decimal_places=0, default=0, help_text='Biaya pendaftaran yang harus dibayar ke rekening ini', max_digits=10, verbose_name='Biaya Pendaftaran (Rp)')),
                ('is_active', models.BooleanField(default=True, help_text='Rekening aktif akan ditampilkan di form pembayaran', verbose_name='Aktif')),
                ('keterangan', models.TextField(blank=True, help_text='Catatan tambahan tentang rekening ini', verbose_name='Keterangan')),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampil di form pembayaran', verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate')),
            ],
            options={
                'verbose_name': 'Rekening Bank',
                'verbose_name_plural': 'Rekening Bank',
                'ordering': ['order', 'nama_bank', 'nomor_rekening'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_pengirim', models.CharField(choices=[('BCA', 'Bank Central Asia (BCA)'), ('BNI', 'Bank Negara Indonesia (BNI)'), ('BRI', 'Bank Rakyat Indonesia (BRI)'), ('Mandiri', 'Bank Mandiri'), ('BSI', 'Bank Syariah Indonesia (BSI)'), ('Lainnya', 'Bank Lainnya')], max_length=50, verbose_name='Bank Pengirim')),
                ('no_rekening_pengirim', models.CharField(blank=True, help_text='Nomor rekening yang digunakan untuk transfer', max_length=50, verbose_name='No. Rekening Pengirim')),
                ('nama_pemilik_rekening', models.CharField(max_length=200, verbose_name='Nama Pemilik Rekening')),
                ('rekening_tujuan', models.CharField(blank=True, help_text='Nomor rekening tujuan transfer', max_length=50, verbose_name='Rekening Tujuan')),
                ('jumlah_transfer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jumlah Transfer (Rp)')),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='bukti_transfer/%Y/%m/%d/', verbose_name='Bukti Transfer')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status Verifikasi')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan (Opsional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Upload')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diupdate')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Verifikasi')),
                ('santri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='admissions.santri', verbose_name='Santri')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'ordering': ['-created_at'],
            },
        ),
    ]
