# Generated by Django 5.2.8 on 2025-12-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('bendahara', 'Bendahara'), ('petugaspendaftaran', 'Petugas Pendaftaran'), ('user', 'User Biasa')], default='petugaspendaftaran', max_length=20, verbose_name='Role'),
        ),
    ]
