"""
Django settings for psb_pondok project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os
from csp.constants import NONCE

# SECRET_KEY - Hardcoded untuk production (ubah jika perlu)
SECRET_KEY = 'django-insecure-l%*@boeybs$z)stf)ld#0*)kjy%ka%e#)(7!lf%089wzc=#%&u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS - Hardcoded untuk production
ALLOWED_HOSTS = [
    'rdsmahato.ponpes.id',
    'www.rdsmahato.ponpes.id',
    'img.rdsmahato.ponpes.id',
    '.rdsmahato.ponpes.id',  # Wildcard untuk semua subdomain
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Untuk format angka Indonesia
    # Third Party Apps
    'django_htmx',
    'widget_tweaks',
    'django_filters',
    'django_extensions',
    'django_summernote',  # Rich Text Editor
    'htmlmin',  # HTML Minification
    'axes',  # Django Axes untuk brute force protection
    'csp',  # Content Security Policy untuk mencegah XSS attacks
    'fontawesomefree',  # Font Awesome Free (static/css dari paket pip)
    # 'compressor',  # CSS/JS Compression - DISABLED karena appconf tidak kompatibel dengan Python 3.10
    # Custom Apps
    'core',
    'users',
    'admissions',
    'documents',  # Documents app
    'payments',
    'admin_panel',  # Menggunakan admin_panel (workaround untuk folder admin-panel)
    'blog',  # Blog/Artikel Management
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',  # Axes middleware - harus setelah AuthenticationMiddleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',  # Content Security Policy middleware - HARUS setelah MessageMiddleware
    # HTMX Middleware - harus setelah AuthenticationMiddleware
    'django_htmx.middleware.HtmxMiddleware',
    # HTML Minification - menggunakan default django-htmlmin
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
]

ROOT_URLCONF = 'psb_pondok.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.website_settings',  # WebsiteSettings untuk semua template
                # 'compressor.context_processors.compress',  # Django Compressor - DISABLED
            ],
        },
    },
]

WSGI_APPLICATION = 'psb_pondok.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'expedien_ponpes',
        'USER': 'expedien',
        'PASSWORD': 'QiAE65Jt*ta19+',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 10,
        },
        # Workaround untuk MariaDB versi lama
        'CONN_MAX_AGE': 0,
    }
}

# Disable RETURNING clause untuk MariaDB 10.4 (tidak support RETURNING)
# Django 5.2+ menggunakan RETURNING untuk INSERT, tapi MariaDB 10.4 tidak support
from django.db.backends.mysql.features import DatabaseFeatures
DatabaseFeatures.can_return_columns_from_insert = False


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'id-id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Static Files Storage - menggunakan ManifestStaticFilesStorage untuk hashing
# File akan di-hash untuk cache busting (contoh: style.css -> style.abc123.css)
# Ini akan otomatis hash file names saat collectstatic
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Static Files Finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # 'compressor.finders.CompressorFinder',  # Django Compressor - DISABLED
]

# Django Compressor Configuration - DISABLED karena appconf tidak kompatibel dengan Python 3.10
# https://django-compressor.readthedocs.io/
# COMPRESS_ENABLED = True  # Aktifkan compression
# COMPRESS_OFFLINE = True  # Pre-compress saat compress command (untuk production)

# Compressor CSS Filters - menggunakan rcssmin untuk minify CSS
# COMPRESS_CSS_FILTERS = [
#     'compressor.filters.css_default.CssAbsoluteFilter',  # Fix relative URLs
#     'compressor.filters.cssmin.rCSSMinFilter',  # Minify CSS dengan rcssmin
# ]

# Compressor JS Filters - menggunakan rjsmin untuk minify JavaScript
# COMPRESS_JS_FILTERS = [
#     'compressor.filters.jsmin.rJSMinFilter',  # Minify JavaScript dengan rjsmin
# ]

# Compressor Storage
# COMPRESS_STORAGE = 'compressor.storage.CompressorFileStorage'

# Compressor Output Settings
# COMPRESS_OUTPUT_DIR = 'CACHE'  # Output directory untuk compressed files
# COMPRESS_CSS_HASHING_METHOD = 'content'  # Hash berdasarkan content
# COMPRESS_JS_HASHING_METHOD = 'content'  # Hash berdasarkan content

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Authentication Backends - Axes harus di akhir
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # Axes backend untuk brute force protection
    'django.contrib.auth.backends.ModelBackend',  # Default Django backend
]

# Login URLs
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'admin-panel:index'
LOGOUT_REDIRECT_URL = 'users:login'  # Redirect ke login setelah logout

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Summernote Configuration
SUMMERNOTE_THEME = 'bs4'  # Bootstrap 4
SUMMERNOTE_CONFIG = {
    'summernote': {
        'width': '100%',
        'height': '500',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'italic', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['fontsize', ['fontsize']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
    },
    'attachment_filesize_limit': 1024 * 1024 * 5,  # 5MB
}

# Production Security Settings
# Security settings untuk production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN'  # SAMEORIGIN untuk support Summernote iframe (bukan DENY)
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Session security
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Session Timeout - 1 jam (3600 detik)
SESSION_COOKIE_AGE = 3600  # 1 jam dalam detik
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session setiap request untuk extend timeout
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session tetap aktif meskipun browser ditutup (sampai timeout)

# SSL/HTTPS settings - Hardcoded untuk production
# Aktifkan redirect HTTP ke HTTPS di level Django (backup jika .htaccess tidak bekerja)
SECURE_SSL_REDIRECT = True  # Redirect semua HTTP request ke HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Untuk reverse proxy/load balancer

# Content Security Policy (CSP) - FORMAT BARU (django-csp >= 4) untuk PRODUCTION
# Menggunakan konfigurasi ketat + upgrade-insecure-requests
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'script-src': (
            "'self'",
            "'unsafe-inline'",   # Masih diperlukan karena Summernote/Alpine/inline script
            "'unsafe-eval'",     # Masih diperlukan untuk Summernote
            "https://cdn.jsdelivr.net",
            "https://code.jquery.com",
            "https://cdnjs.cloudflare.com",
            "https://unpkg.com",  # HTMX CDN
            NONCE,               # Nonce otomatis dari django-csp
        ),
        'style-src': (
            "'self'",
            "'unsafe-inline'",   # Inline style (misal dari Summernote)
            "https://cdn.jsdelivr.net",
            "https://cdnjs.cloudflare.com",
            "https://fonts.googleapis.com",
            NONCE,               # Nonce untuk inline style
        ),
        'img-src': (
            "'self'",
            "data:",
            "https:",
        ),
        'font-src': (
            "'self'",
            "https://fonts.gstatic.com",
            "https://cdnjs.cloudflare.com",
            "data:",
        ),
        'connect-src': ("'self'",),
        'frame-src': ("'self'",),          # Untuk Summernote iframe
        'object-src': ("'none'",),
        'base-uri': ("'self'",),
        'form-action': ("'self'",),
        'frame-ancestors': ("'self'",),
        'upgrade-insecure-requests': True,
    },
    'REPORT_ONLY': False,  # False = enforce CSP
}

# Security Headers tambahan
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Referrer Policy
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'  # COOP
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'  # COEP

# CSRF Protection - Enhanced
CSRF_COOKIE_SAMESITE = 'Strict'  # Strict untuk production
CSRF_USE_SESSIONS = False  # Gunakan cookie-based CSRF
CSRF_COOKIE_AGE = None  # Session-based, expire saat browser close
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'  # Custom view jika diperlukan

# Session Security - Enhanced
SESSION_COOKIE_SAMESITE = 'Strict'  # Strict untuk production
SESSION_COOKIE_NAME = 'sessionid'  # Default Django session cookie name
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Database-backed sessions

# Password Validation - Enhanced
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # Minimum 8 karakter
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django Axes Configuration - Brute Force Protection
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5  # Lock setelah 5 percobaan gagal
AXES_COOLOFF_TIME = 1  # Lock selama 1 jam
AXES_LOCKOUT_CALLABLE = 'axes.lockout.database_lockout'  # Database-based lockout
AXES_LOCKOUT_TEMPLATE = None  # Gunakan default
AXES_LOCKOUT_URL = None  # Gunakan default
AXES_VERBOSE = True  # Log lockout events
AXES_RESET_ON_SUCCESS = True  # Reset counter setelah login berhasil

# Rate Limiting Configuration (menggunakan cache)
# Rate limiting untuk form submission dan API endpoints
RATELIMIT_ENABLE = True  # Enable rate limiting
RATELIMIT_USE_CACHE = 'default'  # Gunakan default cache
RATELIMIT_RATE = '100/h'  # 100 requests per hour per IP (default)
RATELIMIT_KEY = 'ip'  # Rate limit berdasarkan IP address

# Rate limiting untuk endpoint spesifik (dapat di-override di views)
RATELIMIT_LOGIN = '5/m'  # 5 login attempts per minute
RATELIMIT_REGISTER = '3/h'  # 3 registrations per hour per IP
RATELIMIT_FORM_SUBMIT = '20/h'  # 20 form submissions per hour per IP
RATELIMIT_API = '100/h'  # 100 API requests per hour per IP

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB - file kecil di memory
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # Limit jumlah fields
FILE_UPLOAD_PERMISSIONS = 0o644  # File permissions
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755  # Directory permissions

# HTML Minification - Konfigurasi default django-htmlmin untuk Production
# https://github.com/cobrateam/django-htmlmin
HTML_MINIFY = True  # Enable HTML minification (default aktif saat DEBUG=False)

# Exclude URL tertentu dari minifikasi (regex patterns)
EXCLUDE_FROM_MINIFYING = [
    '^admin/',
    '^summernote/',
    '^api/',
    '^static/',
    '^media/',
]

# Keep HTML comments saat minifikasi (default: False = hapus komentar)
KEEP_COMMENTS_ON_MINIFYING = False

# Logging Configuration untuk Production
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django_error.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Security Logging - Production
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'security': {
            'format': 'SECURITY {levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django_error.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'formatter': 'security',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'axes': {
            'handlers': ['console', 'file', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Buat direktori logs jika belum ada
import os
logs_dir = BASE_DIR / 'logs'
if not os.path.exists(logs_dir):
    os.makedirs(logs_dir)
