# Generated by Django 5.2.8 on 2025-11-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='header_mobile_image',
            field=models.ImageField(blank=True, help_text='Gambar header khusus untuk tampilan mobile. Ukuran disarankan: lebar 800px, tinggi 120-150px', null=True, upload_to='settings/', verbose_name='Header Mobile (Kop Surat)'),
        ),
    ]
