# Generated by Django 5.2.8 on 2025-11-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_header_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='header_mobile_height',
            field=models.PositiveIntegerField(default=80, help_text='Tinggi maksimal header mobile dalam pixel. Default: 80px. Disarankan: 60-120px', verbose_name='Tinggi Header Mobile (px)'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='header_mobile_image',
            field=models.ImageField(blank=True, help_text='Gambar header khusus untuk tampilan mobile. Ukuran disarankan: lebar 800-1200px, tinggi 80-100px. Aspect ratio: 10:1 atau 12:1', null=True, upload_to='settings/', verbose_name='Header Mobile (Kop Surat)'),
        ),
    ]
