# Generated by Django 5.2.8 on 2025-12-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_header_mobile_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformasiTambahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Contoh: Waktu Pendaftaran, Dokumen yang Diperlukan', max_length=200, verbose_name='Judul')),
                ('deskripsi', models.TextField(help_text='Isi informasi yang akan ditampilkan', verbose_name='Deskripsi/Isi')),
                ('icon', models.CharField(default='fas fa-info-circle', help_text='Font Awesome icon class (contoh: fas fa-calendar-check)', max_length=100, verbose_name='Icon')),
                ('warna', models.CharField(choices=[('green', 'Hijau'), ('blue', 'Biru'), ('purple', 'Ungu'), ('orange', 'Oranye'), ('red', 'Merah'), ('teal', 'Teal'), ('pink', 'Pink')], default='green', help_text='Warna untuk icon dan background', max_length=20, verbose_name='Warna Icon')),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampil (angka lebih kecil tampil lebih dulu)', verbose_name='Urutan')),
                ('is_published', models.BooleanField(default=True, help_text='Tampilkan di halaman public', verbose_name='Publikasikan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate')),
            ],
            options={
                'verbose_name': 'Informasi Tambahan',
                'verbose_name_plural': 'Informasi Tambahan',
                'ordering': ['order', 'judul'],
            },
        ),
    ]
