# Generated by Django 5.2.8 on 2025-12-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Form A.1, Surat Pernyataan', max_length=200, verbose_name='Nama Template')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, unique=True, verbose_name='Slug')),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi singkat tentang template ini', verbose_name='Deskripsi')),
                ('html_template', models.TextField(help_text='\n        Template HTML dengan placeholder untuk data santri. \n        Gunakan placeholder: {{nama_lengkap}}, {{nisn}}, {{tempat_lahir}}, {{tanggal_lahir}}, {{alamat}}, dll.\n        Contoh: <h1>Nama: {{nama_lengkap}}</h1>\n    ', verbose_name='HTML Template')),
                ('css_template', models.TextField(blank=True, help_text='CSS untuk styling dokumen PDF', verbose_name='CSS Template')),
                ('ukuran_kertas', models.CharField(choices=[('A4', 'A4 (210 x 297 mm)'), ('Letter', 'Letter (8.5 x 11 inch)'), ('Legal', 'Legal (8.5 x 14 inch)')], default='A4', max_length=20, verbose_name='Ukuran Kertas')),
                ('orientasi', models.CharField(choices=[('portrait', 'Portrait (Tegak)'), ('landscape', 'Landscape (Mendatar)')], default='portrait', max_length=20, verbose_name='Orientasi')),
                ('margin_top', models.CharField(default='1.5cm', help_text='Contoh: 1.5cm, 15mm, 0.5in', max_length=20, verbose_name='Margin Atas')),
                ('margin_right', models.CharField(default='1.5cm', max_length=20, verbose_name='Margin Kanan')),
                ('margin_bottom', models.CharField(default='1.5cm', max_length=20, verbose_name='Margin Bawah')),
                ('margin_left', models.CharField(default='1.5cm', max_length=20, verbose_name='Margin Kiri')),
                ('is_active', models.BooleanField(default=True, help_text='Template aktif bisa digunakan untuk generate PDF', verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampil di list', verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate')),
            ],
            options={
                'verbose_name': 'Template Dokumen',
                'verbose_name_plural': 'Template Dokumen',
                'ordering': ['order', 'nama'],
            },
        ),
    ]
