# Generated by Django 5.2.8 on 2025-11-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nama File Asli')),
                ('webp_image', models.ImageField(upload_to='converted/%Y/%m/%d/', verbose_name='Gambar WebP')),
                ('original_size', models.BigIntegerField(verbose_name='Ukuran Asli (bytes)')),
                ('converted_size', models.BigIntegerField(verbose_name='Ukuran WebP (bytes)')),
                ('compression_ratio', models.FloatField(verbose_name='Rasio Kompresi (%)')),
                ('quality', models.IntegerField(default=85, verbose_name='Kualitas WebP')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Lebar (px)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Tinggi (px)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Gambar yang Dikonversi',
                'verbose_name_plural': 'Gambar yang Dikonversi',
                'ordering': ['-created_at'],
            },
        ),
    ]
