# Generated by Django 5.2.8 on 2025-11-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/images/%Y/%m/%d/', verbose_name='Gambar')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt Text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
            ],
            options={
                'verbose_name': 'Gambar Blog',
                'verbose_name_plural': 'Gambar Blog',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Konten')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Ringkasan')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/featured/%Y/%m/%d/', verbose_name='Gambar Utama')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='blog/videos/%Y/%m/%d/', verbose_name='File Video')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('shares_count', models.PositiveIntegerField(default=0, verbose_name='Shares')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Publikasi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Unggulan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate')),
            ],
            options={
                'verbose_name': 'Artikel Blog',
                'verbose_name_plural': 'Artikel Blog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('konten', models.TextField(verbose_name='Konten')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='pengumuman/%Y/%m/%d/', verbose_name='Gambar')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status')),
                ('is_penting', models.BooleanField(default=False, verbose_name='Penting')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Publikasi')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate')),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
                'ordering': ['-is_penting', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nama')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimoni/%Y/%m/%d/', verbose_name='Foto')),
                ('jabatan', models.CharField(blank=True, max_length=200, verbose_name='Jabatan/Alumni')),
                ('testimoni', models.TextField(verbose_name='Testimoni')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Rating')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
            ],
            options={
                'verbose_name': 'Testimoni',
                'verbose_name_plural': 'Testimoni',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
